/*
 * This source file was generated by the Gradle 'init' task
 */
package io.mattdickson

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main(args: Array<String>) {
    val day = args[0]
    println(App().greeting + day)
}
